"""Generate streamlit_app.py via Python to avoid encoding corruption."""
import os

TARGET = os.path.join(os.path.dirname(__file__), "streamlit_app.py")

lines = []
def L(s=""):
    lines.append(s)

# ── File Header ──
L("# RAG Engineering Study — Streamlit Dashboard")
L("# Tracks: Retrieval Engineering | Graph-Based Retrieval | Context & Memory Optimization")
L("# Dataset: LegalBench-RAG (CUAD, MAUD, ContractNLI, PrivacyQA)")
L("# Run: streamlit run streamlit_app.py")
L("")
L("import json, os")
L("import pandas as pd")
L("import numpy as np")
L("import streamlit as st")
L("")
L("# PAGE CONFIG")
L('st.set_page_config(page_title="RAG Engineering Study Dashboard", page_icon="📊", layout="wide")')
L("")
L("# ── DATA LOADING ──")
L("def _load_json(path):")
L("    try:")
L('        with open(path, "r", encoding="utf-8") as f:')
L("            return json.load(f)")
L("    except Exception as e:")
L('        st.warning(f"Could not load {os.path.basename(path)}: {e}")')
L("        return None")
L("")
L("def load_results(data_dir='results/'):")
L("    patterns = {")
L('        "track1_baseline": "track1_baseline.json",')
L('        "track1_chunking": "track1_chunking.json",')
L('        "track1_retrieval": "track1_retrieval.json",')
L('        "track1_reranking": "track1_reranking.json",')
L('        "track1_transform": "track1_transform.json",')
L('        "track1_final": "track1_final.json",')
L('        "track2_chunking": "track2_chunking.json",')
L('        "track2_graph_search": "track2_graph_search.json",')
L('        "track2_communities": "track2_communities.json",')
L('        "track2_routed": "track2_routed.json",')
L('        "track2_final": "track2_final.json",')
L('        "track3_prompt_versioning": "track3_prompt_versioning.json",')
L('        "track3_compression": "track3_compression.json",')
L('        "track3_memory": "track3_memory.json",')
L('        "track3_caching": "track3_caching.json",')
L('        "track3_fullcontext": "track3_fullcontext.json",')
L('        "track3_final": "track3_final.json",')
L("    }")
L("    return {k: _load_json(os.path.join(data_dir, fn)) for k, fn in patterns.items()}")
L("")
L("# ── FALLBACK DEMO DATA ──")
L("SAMPLE = {")
L('    "track1_baseline": {"faithfulness": 0.617, "precision": 0.987, "recall": 0.803, "relevance": 0.733, "hit_rate@5": 0.667, "latency_ms": 1667},')
L('    "track1_chunking": {')
L('        "fixed-token": {"faithfulness": 0.617, "precision": 0.987, "recall": 0.803, "relevance": 0.733, "hit_rate@5": 0.667},')
L('        "semantic": {"faithfulness": 0.620, "precision": 0.980, "recall": 0.810, "relevance": 0.740, "hit_rate@5": 0.700},')
L('        "parent-child": {"faithfulness": 0.605, "precision": 0.970, "recall": 0.795, "relevance": 0.715, "hit_rate@5": 0.633},')
L("    },")
L('    "track1_retrieval": {')
L('        "dense": {"faithfulness": 0.620, "precision": 0.980, "recall": 0.810, "relevance": 0.740, "hit_rate@5": 0.700, "latency_ms": 1550},')
L('        "keyword": {"faithfulness": 0.590, "precision": 0.950, "recall": 0.780, "relevance": 0.710, "hit_rate@5": 0.600, "latency_ms": 1320},')
L('        "hybrid": {"faithfulness": 0.633, "precision": 1.000, "recall": 0.817, "relevance": 0.720, "hit_rate@5": 0.933, "latency_ms": 1857},')
L("    },")
L('    "track1_reranking": {')
L('        "no-rerank": {"faithfulness": 0.620, "precision": 0.930, "recall": 0.800, "relevance": 0.710, "hit_rate@5": 0.833},')
L('        "rerank": {"faithfulness": 0.633, "precision": 1.000, "recall": 0.817, "relevance": 0.720, "hit_rate@5": 0.933},')
L("    },")
L('    "track1_transform": {')
L('        "none": {"faithfulness": 0.633, "precision": 1.000, "recall": 0.817, "relevance": 0.720, "hit_rate@5": 0.933},')
L('        "hyde": {"faithfulness": 0.620, "precision": 0.970, "recall": 0.805, "relevance": 0.725, "hit_rate@5": 0.900},')
L('        "multi-query": {"faithfulness": 0.615, "precision": 0.960, "recall": 0.800, "relevance": 0.710, "hit_rate@5": 0.867},')
L("    },")
L('    "track1_final": {"faithfulness": 0.633, "precision": 1.000, "recall": 0.817, "relevance": 0.720, "hit_rate@5": 0.933, "latency_ms": 1857},')
L('    "track2_chunking": {')
L('        "fixed-token": {"faithfulness": 0.617, "precision": 0.987, "recall": 0.803, "relevance": 0.733, "hit_rate@5": 0.667, "latency_ms": 1667},')
L('        "structured": {"faithfulness": 0.600, "precision": 0.950, "recall": 0.800, "relevance": 0.620, "hit_rate@5": 0.433, "latency_ms": 2200},')
L("    },")
L('    "track2_graph_search": {')
L('        "graph-1hop": {"faithfulness": 0.590, "precision": 0.930, "recall": 0.780, "relevance": 0.560, "hit_rate@5": 0.367, "latency_ms": 2100},')
L('        "dense": {"faithfulness": 0.600, "precision": 0.960, "recall": 0.810, "relevance": 0.580, "hit_rate@5": 0.433, "latency_ms": 2660},')
L("    },")
L('    "track2_communities": {"community_count": 0, "synthesis_results": None, "note": "No communities found - graph too small for community detection"},')
L('    "track2_routed": {')
L("        'factual_count': 85, 'relationship_count': 20, 'synthesis_count': 10, 'total_queries': 115,")
L("        'fallback_rate': 0.53, 'distribution': {'factual': 85, 'relationship': 20, 'synthesis': 10},")
L("        'entities_total': 180, 'entities_unique': 17, 'graph_nodes': 17, 'graph_edges': 1,")
L("    },")
L('    "track2_final": {"faithfulness": 0.600, "precision": 0.960, "recall": 0.810, "relevance": 0.580, "hit_rate@5": 0.433, "latency_ms": 2660},')
L("    # ... (rest truncated for write tool)")
L("}")
L("")
L("print('Module loaded')")
L("print(f'File: {__file__}')")

with open(TARGET, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote {len(lines)} lines to {TARGET}")
