import os

TARGET = r'C:\Users\adm\.openclaw-autoclaw\agents\task-2-rag\workspace\rag-study\DELIVERY\streamlit_app.py'

code_lines = []
def L(s=''):
    code_lines.append(s)

L('')
L('# === CONSTANTS & HELPERS ===')
L('')
L('METRIC_LABELS = {')
L('    "faithfulness": "Faithfulness",')
L('    "precision": "Precision",')
L('    "recall": "Recall",')
L('    "relevance": "Relevance",')
L('    "hit_rate@5": "Hit Rate@5",')
L('    "latency_ms": "Latency (ms)"')
L('}')
L('METRICS_BASIC = ["faithfulness","precision","recall","relevance","hit_rate@5"]')
L('METRICS_ALL = METRICS_BASIC + ["latency_ms"]')
L('')

L('def _highlight_best_worst(df, higher_better_cols, lower_better_cols=None):')
L('    if lower_better_cols is None:')
L('        lower_better_cols = []')
L('    def _hl(s):')
L('        cname = s.name')
L('        if cname in higher_better_cols:')
L('            best_fn, worst_fn = "idxmax", "idxmin"')
L('        elif cname in lower_better_cols:')
L('            best_fn, worst_fn = "idxmin", "idxmax"')
L('        else:')
L('            return [""] * len(s)')
L('        styles = [""] * len(s)')
L('        try:')
L('            styles[s.idxmax()] = "background-color: #d4edda; font-weight: bold;"')
L('        except:')
L('            pass')
L('        try:')
L('            styles[s.idxmin()] = "background-color: #f8d7da;"')
L('        except:')
L('            pass')
L('        return styles')
L('    return df.style.apply(_hl)')
L('')

L('def build_comparison_df(configs, metrics=None):')
L('    if metrics is None:')
L('        metrics = METRICS_ALL')
L('    rows = []')
L('    for cfg_name, data in configs.items():')
L('        if data is None:')
L('            continue')
L('        row = {"Configuration": cfg_name}')
L('        for m in metrics:')
L('            val = data.get(m, data.get(m.replace("@","_at_"), None))')
L('            if val is not None:')
L('                row[m] = int(val) if m == "latency_ms" else round(val, 3)')
L('        rows.append(row)')
L('    return pd.DataFrame(rows)')
L('')

L('def render_metric_bar_chart(df, metric_cols, title):')
L('    chart_df = df.set_index("Configuration")[metric_cols]')
L('    st.bar_chart(chart_df, height=400)')
L('    st.caption(title)')
L('')

L('def render_delta_table(df, baseline_name, compare_name, metrics=None):')
L('    if metrics is None:')
L('        metrics = METRICS_ALL')
L('    b = df[df["Configuration"] == baseline_name]')
L('    c = df[df["Configuration"] == compare_name]')
L('    if b.empty or c.empty:')
L('        st.warning("Cannot compute delta - missing data.")')
L('        return')
L('    b = b.iloc[0]; c = c.iloc[0]')
L('    rows = []')
L('    for m in metrics:')
L('        bv, cv = b.get(m), c.get(m)')
L('        if bv is None or cv is None:')
L('            continue')
L('        if m == "latency_ms":')
L('            d = cv - bv')
L('            ds = f"{d:+.0f} ms"')
L('            better = d < 0')
L('        else:')
L('            d = cv - bv')
L('            ds = f"{d:+.3f}"')
L('            better = d > 0')
L('        rows.append({"Metric": METRIC_LABELS.get(m, m),')
L('                      baseline_name: bv,')
L('                      compare_name: cv,')
L('                      "Delta": ds,')
L('                      "Better": chr(9989) if better else (chr(10060) if d != 0 else chr(8212))})')
L('    st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)')
L('')

L('def render_metric_card_bg(bg, label, value, help_text=None):')
L('    ht = f\'<div style="font-size:0.75rem; color:#666; margin-top:4px;">{help_text}</div>\' if help_text else ""')
L('    st.markdown(f"""')
L('    <div style="background:{bg}; padding:16px 20px; border-radius:8px; margin-bottom:8px;')
L('                border-left:4px solid #2e7d32;">')
L('        <div style="font-size:0.85rem; color:#555;">{label}</div>')
L('        <div style="font-size:1.8rem; font-weight:700; color:#1e3a5f;">{value}</div>')
L('        {ht}')
L('    </div>""", unsafe_allow_html=True)')
L('')

L('def render_dark_card(label, value, help_text=None):')
L('    ht = f\'<div style="font-size:0.75rem; color:#a0c4e8; margin-top:4px;">{help_text}</div>\' if help_text else ""')
L('    st.markdown(f"""')
L('    <div style="background:#1e3a5f; padding:16px 20px; border-radius:8px; margin-bottom:8px;')
L('                border-left:4px solid #4a90d9;">')
L('        <div style="font-size:0.85rem; color:#a0c4e8;">{label}</div>')
L('        <div style="font-size:1.8rem; font-weight:700; color:#fff;">{value}</div>')
L('        {ht}')
L('    </div>""", unsafe_allow_html=True)')
L('')

# Append to existing file
with open(TARGET, 'a', encoding='utf-8') as f:
    f.write('\n'.join(code_lines))

print(f"Appended {len(code_lines)} lines, file now {os.path.getsize(TARGET)} bytes")
