import os

TARGET = r"C:\Users\adm\.openclaw-autoclaw\agents\task-2-rag\workspace\rag-study\DELIVERY\streamlit_app.py"
code_lines = []
def L(s=""):
    code_lines.append(s)

L("def page_track2(data, _sample):")
L("    st.header('Track 2: Graph-Based Retrieval')")
L("    st.markdown('**Goal:** Enhance retrieval with entity extraction, graph search, communities, and routing.')")
L("    bl = data.get('track1_baseline') or {}")
L("    t2 = data.get('track2_final') or {}")
L("    if t2:")
L("        c1, c2, c3 = st.columns(3)")
L("        fb = t2.get('faithfulness',0) - bl.get('faithfulness',0)")
L("        hb = t2.get('hit_rate@5',0) - bl.get('hit_rate@5',0)")
L("        lb = int(t2.get('latency_ms',0)) - int(bl.get('latency_ms',0))")
L("        with c1: st.metric('Faithfulness', t2.get('faithfulness','---'), f'{fb:+.3f}' if bl else None)")
L("        with c2: st.metric('Hit Rate@5', t2.get('hit_rate@5','---'), f'{hb:+.3f}' if bl else None)")
L("        with c3: st.metric('Latency', f\"{int(t2.get('latency_ms',0))} ms\", f'{lb:+d} ms' if bl else None)")
L("    st.divider()")
L("")
L("    with st.expander('S2: Structured Chunking', expanded=False):")
L("        d = data.get('track2_chunking')")
L("        if d:")
L("            st.dataframe(build_comparison_df(d, METRICS_BASIC + ['latency_ms']), use_container_width=True, hide_index=True)")
L("")
L("    with st.expander('S3: Entity Extraction', expanded=False):")
L("        r = data.get('track2_routed')")
L("        if r:")
L("            c1, c2 = st.columns(2)")
L("            with c1: st.metric('Total Entities Extracted', r.get('entities_total','---'))")
L("            with c2: st.metric('Unique Entities', r.get('entities_unique','---'))")
L("            dist = r.get('distribution', {})")
L("            if dist:")
L("                st.markdown('**Entity Type Distribution**')")
L("                st.bar_chart(pd.DataFrame({'Type': list(dist.keys()), 'Count': list(dist.values())}).set_index('Type'), height=300)")
L("")
L("    with st.expander('S4: Graph Search Comparison', expanded=False):")
L("        d = data.get('track2_graph_search')")
L("        if d:")
L("            st.dataframe(build_comparison_df(d, METRICS_BASIC + ['latency_ms']), use_container_width=True, hide_index=True)")
L("")
L("    with st.expander('S5: Community Detection', expanded=False):")
L("        d = data.get('track2_communities')")
L("        if d:")
L("            st.metric('Communities Found', d.get('community_count','---'))")
L("            if d.get('note'): st.warning(d['note'])")
L("")
L("    with st.expander('S6: Routing Layer', expanded=False):")
L("        r = data.get('track2_routed')")
L("        if r:")
L("            dist = r.get('distribution', {})")
L("            if dist:")
L("                st.markdown('**Query Routing Distribution**')")
L("                st.bar_chart(pd.DataFrame({'Route Type': list(dist.keys()), 'Count': list(dist.values())}).set_index('Route Type'), height=300)")
L("            st.metric('Fallback Rate', f\"{r.get('fallback_rate',0):.0%}\", help='Queries falling back to dense retrieval')")
L("            col1, col2 = st.columns(2)")
L("            with col1: st.metric('Graph Nodes', r.get('graph_nodes','---'))")
L("            with col2: st.metric('Graph Edges', r.get('graph_edges','---'))")
L("")
L("    st.subheader('T2 Final vs Baseline')")
L("    if t2 and bl:")
L("        render_delta_table(build_comparison_df({'Baseline': bl, 'Track 2 Final': t2}), 'Baseline', 'Track 2 Final')")
L("    st.warning('Key insight: Graph too sparse (17 nodes, 1 edge) - FLAN-T5-XL entity extraction insufficient at 3B scale for legal documents. 53% query fallback rate indicates the graph rarely contributes useful signals.')")
L("")

with open(TARGET, "a", encoding="utf-8") as f:
    f.write("\n".join(code_lines))

print(f"Part 3c appended {len(code_lines)} lines, file now {os.path.getsize(TARGET)} bytes")
