import os

TARGET = r"C:\Users\adm\.openclaw-autoclaw\agents\task-2-rag\workspace\rag-study\DELIVERY\streamlit_app.py"
code_lines = []
def L(s=""):
    code_lines.append(s)

L("def page_track1(data, _sample):")
L("    st.header('Track 1: Retrieval Engineering')")
L("    st.markdown('**Goal:** Optimize retrieval pipeline - chunking, retrieval mode, reranking, query transform')")
L("    bl = data.get('track1_baseline') or {}")
L("    t1 = data.get('track1_final') or {}")
L("    if t1:")
L("        c1, c2, c3 = st.columns(3)")
L("        fb = t1.get('faithfulness',0) - bl.get('faithfulness',0)")
L("        hb = t1.get('hit_rate@5',0) - bl.get('hit_rate@5',0)")
L("        lb = int(t1.get('latency_ms',0)) - int(bl.get('latency_ms',0))")
L("        with c1: st.metric('Faithfulness', t1.get('faithfulness','---'), f'{fb:+.3f}' if bl else None)")
L("        with c2: st.metric('Hit Rate@5', t1.get('hit_rate@5','---'), f'{hb:+.3f}' if bl else None)")
L("        with c3: st.metric('Latency', f\"{int(t1.get('latency_ms',0))} ms\", f'{lb:+d} ms' if bl else None)")
L("    st.divider()")
L("")
L("    with st.expander('S1: Baseline (OpenAI Ada-002 + Full Context)', expanded=False):")
L("        st.markdown('Fixed-token chunking, Dense retrieval, No reranking, No query transform, Full context.')")
L("        if bl:")
L("            df = pd.DataFrame([bl])[['faithfulness','precision','recall','relevance','hit_rate@5','latency_ms']]")
L("            df.columns = [METRIC_LABELS[c] for c in df.columns]")
L("            st.dataframe(df, use_container_width=True, hide_index=True)")
L("")
L("    with st.expander('S2: Chunking Strategy Comparison', expanded=False):")
L("        st.markdown('**Three methods**: fixed-token, semantic, parent-child.')")
L("        d = data.get('track1_chunking')")
L("        if d:")
L("            df = build_comparison_df(d, METRICS_BASIC)")
L("            render_metric_bar_chart(df, METRICS_BASIC, 'Chunking Strategy Comparison')")
L("")
L("    with st.expander('S3: Retrieval Mode Comparison', expanded=False):")
L("        st.markdown('**Dense vs Keyword vs Hybrid.**')")
L("        d = data.get('track1_retrieval')")
L("        if d:")
L("            df = build_comparison_df(d, METRICS_BASIC + ['latency_ms'])")
L("            render_metric_bar_chart(df, METRICS_BASIC, 'Retrieval Mode Comparison')")
L("            st.caption('Latency: ' + ', '.join(f\"{k}: {int(v.get('latency_ms',0))}ms\" for k,v in d.items()))")
L("")
L("    with st.expander('S4: Reranking Comparison', expanded=False):")
L("        d = data.get('track1_reranking')")
L("        if d:")
L("            st.dataframe(build_comparison_df(d, METRICS_BASIC), use_container_width=True, hide_index=True)")
L("")
L("    with st.expander('S5: Query Transform Comparison', expanded=False):")
L("        d = data.get('track1_transform')")
L("        if d:")
L("            st.dataframe(build_comparison_df(d, METRICS_BASIC), use_container_width=True, hide_index=True)")
L("")
L("    st.subheader('T1 Final vs Baseline')")
L("    if t1 and bl:")
L("        render_delta_table(build_comparison_df({'Baseline': bl, 'Track 1 Final': t1}), 'Baseline', 'Track 1 Final')")
L("    st.info('Key insight: Hybrid retrieval wins: **+40% hit_rate@5** (0.667 to 0.933). Dense + keyword search dramatically improves coverage at rank 5.')")
L("")

with open(TARGET, "a", encoding="utf-8") as f:
    f.write("\n".join(code_lines))

print(f"Part 3b appended {len(code_lines)} lines, file now {os.path.getsize(TARGET)} bytes")
